skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_staking_core = "HFpN1kKDxGdS8XG9NAP63gA4dkzMvrE8hofP9Xi1NgPm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
